# Generated by Django 5.0.4 on 2024-04-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='phone',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
        migrations.RemoveField(
            model_name='record',
            name='province',
        ),
    ]
