# Generated by Django 5.0.4 on 2024-04-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
